name: NPM Publish

on:
  workflow_call:
    inputs:
      fetch-depth:
        description: Number of commits to fetch. 0 indicates all history for all branches and tags.
        default: 1
        type: number
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ inputs.fetch-depth }}
      - uses: bloq/actions/publish-to-npm@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
