name: Tag Update

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  update-major-version-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          COMMIT_SHA=$(git rev-list --max-count=1 "$GITHUB_REF")
          AUTHOR_NAME=$(git log --format='%an' --max-count=1 "$COMMIT_SHA")
          AUTHOR_EMAIL=$(git log --format='%ae' --max-count=1 "$COMMIT_SHA")
          git config user.name "$AUTHOR_NAME"
          git config user.email "$AUTHOR_EMAIL"
      - run: |
          MAJOR_VERSION=$(echo "$GITHUB_REF" | grep -oP '^v\d+')
          git tag --force "$MAJOR_VERSION"
          git push --force --tags
